#!/usr/bin/php
<?php
require "vendor/autoload.php";
use PHPHtmlParser\Dom;
use Playground\Downloader;

echo "Starting script: \n";

$dom = new Dom;
$url = "http://www.xvideos.com";
$directory = "thumbs";

$downloader = new Downloader($dom, $url, $directory);
$downloader->loadSiteHTML();

$directory = "thumbs";
mkdir($directory);

$time_start = microtime(true);
$downloader->makeDownload();

$time_end = microtime(true);
$total_time = $time_end - $time_start;
echo "Executed in : {$total_time} seconds \n";
