#!/usr/bin/php
<?php
require "vendor/autoload.php";
use PHPHtmlParser\Dom;
use Playground\Downloader;
use Playground\DownloadThumbsAtHome;

echo "Welcome to Adult Playground\n";
echo "A script that allow you download content from a funny web site =D\n";

$actions = [
    '--download-thumbs' => 'Playground\DownloadThumbsAtHome'
];

$allowed_actions = array_keys($actions);

if (sizeof($argv) == 1 || !in_array($argv[1], $allowed_actions)) {
    echo "\nOptions:\n";
    echo "--download-thumbs          Download all thumbs from homepage\n";
}
else {
    $dom = new Dom;
    $url = "http://www.xvideos.com";
    $directory = "thumbs";

    $downloader = new Downloader($dom, $url);
    $downloader->loadSiteHTML();

    $downloadStrategy = new $actions[$argv[1]]($directory);

    mkdir($directory);

    $downloader->makeDownload($downloadStrategy);

    echo "Executed in : {$downloader->getTotalExecutionTime()} seconds \n";
}
